language: c
install: "sudo apt-get update;sudo apt-get install ocaml-nox"
sudo: required
script:
 - wget https://coq.inria.fr/distrib/V8.5pl3/files/coq-8.5pl3.tar.gz
 - tar xf coq-8.5pl3.tar.gz
 - cd coq-8.5pl3
 - ./configure
 - make
 - echo Hello, World!!
