language: c
install: "sudo apt-get install ocaml-nox camlp4"
sudo: required
script:
 - wget https://coq.inria.fr/distrib/V8.5pl3/files/coq-8.5pl3.tar.gz
 - tar xf coq-8.5pl3.tar.gz
 - cd coq-8.5pl3
 - which camlp4
 - ocamlc -version
 - ocamlc -where
 - camlp4orf -v
 - ls /usr/lib/ocaml/camlp4
 - ./configure
 - make
 - echo Hello, World!!
